version: '3'
services:
    app:
        build:
            context: .
            args:
                - NODE_ENV=development
        command: ./node_modules/.bin/nodemon -L --inspect=0.0.0.0:9229 server.js
        volumes:
            - .:/srv/app
            - /srv/app/node_modules
        depends_on:
            - mysql
        expose:
            - 3000
            - 9229
        ports:
            - 3000:3000
            - 9229:9229
        restart: always
        env_file:
            - .env
        environment:
            - NODE_ENV=development
            - DATABASE_URL=mysql://root@mysql/test
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./.db/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: test
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        logging:
            driver: none
